
// Автоматически генерируемый файл ресурсов.
// Не редактируйте его.
// Автор: Шаталов С.В.
// Sun Jun 18 04:40:59 2023

#pragma once

struct _z {
	struct _R {
		struct _drawable {
			enum { 
				font1	= 0x00100000, 	font2	= 0x00100001, 	font3	= 0x00100002, 
				fontDefault	= 0x00100003, 	znull	= 0x00100004, 	zssh	= 0x00100005, 
			};
		}; 
		_drawable drawable;
		struct _color {
			enum { 
				black	= 0xFF000000, 	silver	= 0xFFC0C0C0, 	maroon	= 0xFF000080, 
				red	= 0xFF0000FF, 	navy	= 0xFF800000, 	blue	= 0xFFFF0000, 
				purple	= 0xFF800080, 	fuchsia	= 0xFFFF00FF, 	green	= 0xFF008000, 
				lime	= 0xFF00FF00, 	olive	= 0xFF008080, 	yellow	= 0xFF00F0F0, 
				teal	= 0xFF808000, 	aqua	= 0xFFFFFF00, 	gray	= 0xFF808080, 
				white	= 0xFFFFFFFF, 	themeDark	= 0xFFED2E4A, 	themeLight	= 0xFF2376B8, 
				selectorDark	= 0xFFA000A0, 	selectorLight	= 0xFFA0A000, 	dividerDark	= 0xFF755C5C, 
				dividerLight	= 0xFF4F4F4F, 	highlightTextDark	= 0xFFF17056, 
				highlightTextLight	= 0xFF5670F1, 	messageTextDark	= 0xFFD2FA64, 
				messageTextLight	= 0xFFD2FA64, 	headerTextDark	= 0xFFCFBA41, 
				headerTextLight	= 0xFF45F1A9, 	linkTextDark	= 0xFFB8FA01, 
				linkTextLight	= 0xFFA0A0A0, 	textTextDark	= 0xFF9599F7, 	textTextLight	= 0xFFEA5191, 
				tabDark	= 0xFFA0A000, 	tabLight	= 0xFF00A0A0, 	tabTextDark	= 0xFFB0B000, 
				tabTextLight	= 0xFF007070, 	progressDark	= 0x80909090, 	progressLight	= 0x80505050, 
				progressPrimaryDark	= 0xFFFF7000, 	progressPrimaryLight	= 0xFF00FF00, 
				progressSecondaryDark	= 0xFFA03000, 	progressSecondaryLight	= 0xFF00A000, 
				progressTextDark	= 0xFFB0B0B0, 	progressTextLight	= 0xFFFFFFFF, 
				sliderTextDark	= 0xFFE0E0E0, 	sliderTextLight	= 0xFFE0E0E0, 
				menuDark	= 0xFFAF4001, 	menuLight	= 0xFF00406F, 	menuTextDark	= 0xFFFFFFFF, 
				menuTextLight	= 0xFFFFFFFF, 	hintTextDark	= 0xFF909090, 	hintTextLight	= 0xFF909090, 
			};
		}; 
		_color color;
		struct _dimen {
			enum { 
				toastMinWidth	= 75, 	toastMinHeight	= 30, 	videoMinWidth	= 120, 
				videoMinHeight	= 100, 	imageMinWidth	= 24, 	imageMinHeight	= 24, 
				actionMinWidth	= 30, 	actionMinHeight	= 30, 	textMinWidth	= 30, 
				textMinHeight	= 10, 	butMinWidth	= 80, 	butMinHeight	= 25, 
				toolsMinWidth	= 50, 	toolsMinHeight	= 50, 	checkMinWidth	= 50, 
				checkMinHeight	= 20, 	radioMinWidth	= 50, 	radioMinHeight	= 20, 
				headerMinWidth	= 50, 	headerMinHeight	= 20, 	controllerMinWidth	= 96, 
				controllerMinHeight	= 96, 	switchMinWidth	= 70, 	switchMinHeight	= 30, 
				progressMinWidth	= 70, 	progressMinHeight	= 22, 	progressMaxWidth	= 150, 
				progressMaxHeight	= 22, 	sliderMinWidth	= 90, 	sliderMinHeight	= 25, 
				sliderMaxWidth	= 150, 	sliderMaxHeight	= 35, 	selectMinWidth	= 60, 
				selectMinHeight	= 30, 	chartMinWidth	= 12, 	chartMinHeight	= 5, 
				editMinWidth	= 110, 	editMinHeight	= 30, 	divider	= 2, 	menuText	= 15, 
				hintText	= 14, 	textText	= 16, 	messageText	= 22, 	headerText	= 17, 
			};
		}; 
		_dimen dimen;
		struct _id {
			enum { 
				ccontroller	= 0x00101000, 	acontroller	= 0x00101001, 	menuApp	= 0x00101002, 
				menuOverflow	= 0x00101003, 	ok	= 0x00101004, 	yes	= 0x00101005, 
				no	= 0x00101006, 	def	= 0x00101007, 	toast	= 0x00101008, 
				actionBar	= 0x00101009, 	wndPopup	= 0x0010100A, 	root	= 0x0010100B, 
				common	= 0x0010100C, 	keyboard	= 0x0010100D, 	list1	= 0x0010100E, 
				edit1	= 0x0010100F, 	button1	= 0x00101010, 	switch1	= 0x00101011, 
				seek	= 0x00101012, 	progress1	= 0x00101013, 	select	= 0x00101014, 
				grid1	= 0x00101015, 	radioDark	= 0x00101016, 	chkbox	= 0x00101017, 
				radioLight	= 0x00101018, 	button2	= 0x00101019, 	switch2	= 0x0010101A, 
				switch3	= 0x0010101B, 	button3	= 0x0010101C, 	seek1	= 0x0010101D, 
				button11	= 0x0010101E, 	seek2	= 0x0010101F, 	button4	= 0x00101020, 
				edit2	= 0x00101021, 	progress2	= 0x00101022, 	form	= 0x00101023, 
			};
		}; 
		_id id;
		struct _integer {
			enum { 
				MENU_BROWSER	= 1001, 	MENU_SETTINGS	= 1002, 	MENU_PROPS	= 1003, 
				MENU_MODEL	= 1004, 	MENU_RESET	= 1005, 	MENU_RESTORE	= 1006, 
				MENU_EXIT	= 1007, 	MENU_KEYBOARD	= 1008, 	MENU_JOYSTICK	= 1009, 
				MENU_PROPS_SOUND	= 1010, 	MENU_PROPS_MAGNITOPHON	= 1011, 
				MENU_PROPS_FILTER	= 1012, 	MENU_PROPS_TURBO	= 1013, 	MENU_PROPS_EXECUTE	= 1014, 
				MENU_PROPS_DEBUGGER	= 1015, 	MENU_DEBUGGER_LABEL	= 1016, 
				MENU_DEBUGGER_CODE	= 1017, 	MENU_DEBUGGER_VALUE	= 1018, 	MENU_MRU	= 1019, 
				MENU_OPERATIONS	= 1020, 	MENU_SHOW_DEBUGGER	= 1021, 	MENU_DEBUGGER1	= 1022, 
				MENU_POKES	= 1023, 	MENU_MAGIC	= 1024, 	MENU_ASSEMBLER	= 1025, 
				MENU_EDITOR_TZX	= 1026, 	MENU_MODEL_48KS	= 1300, 	MENU_MODEL_128K	= 1301, 
				MENU_MODEL_PENTAGON	= 1302, 	MENU_MODEL_SCORPION	= 1303, 
				MENU_MRU_1	= 1400, 	MENU_MRU_2	= 1401, 	MENU_MRU_3	= 1402, 
				MENU_MRU_4	= 1403, 	MENU_MRU_5	= 1404, 	MENU_MRU_6	= 1405, 
				MENU_MRU_7	= 1406, 	MENU_MRU_8	= 1407, 	MENU_MRU_9	= 1408, 
				MENU_MRU_10	= 1409, 	ccontrol	= 0, 	iconAppZx	= 1, 	zxBar	= 2, 
				iconEditEx	= 3, 	ellips	= 4, 	ellipsDiag	= 5, 	ccontrolL	= 6, 
				ccontrolU	= 7, 	ccontrolR	= 8, 	ccontrolD	= 9, 	acontrol	= 10, 
				acontrolY	= 11, 	acontrolX	= 12, 	acontrolA	= 13, 	acontrolB	= 14, 
				horzGlow	= 15, 	vertGlow	= 16, 	progressWait	= 17, 	iconEdit	= 18, 
				iconGroup	= 19, 	rect	= 20, 	rectRound	= 21, 	gradient	= 22, 
				gradientDiag	= 23, 	gradientRadial	= 24, 	iconBullet	= 25, 
				edit	= 26, 	toolsTriLimit	= 27, 	toolsTri	= 28, 	tools	= 29, 
				header	= 30, 	button1	= 31, 	button2	= 32, 	button3	= 33, 
				button4	= 34, 	switchTrack	= 35, 	switchTrumb	= 36, 	selectDrop	= 37, 
				selectItem	= 38, 	selectCapt	= 39, 	radioOff	= 40, 	radioOn	= 41, 
				checkOff	= 42, 	checkOn	= 43, 	sliderTrumb2	= 44, 	sliderTrumb1	= 45, 
				sliderTrack2	= 46, 	sliderTrack1	= 47, 	formBackground	= 48, 
				butKeyboardSmall	= 49, 	butKeyboardLarge	= 50, 	iconBack	= 51, 
				iconBasket	= 52, 	iconTraceExit	= 53, 	iconDisk	= 54, 	iconDef	= 55, 
				iconBp	= 56, 	iconTraceStep	= 57, 	iconMru	= 58, 	iconHex	= 59, 
				iconForward	= 60, 	iconDel	= 61, 	iconTzx	= 62, 	iconDebug	= 63, 
				iconFind	= 64, 	iconContent	= 65, 	iconAccelOn	= 66, 	iconKeyb	= 67, 
				iconNo	= 68, 	iconInsert	= 69, 	iconHelp	= 70, 	iconTrDos	= 71, 
				icon16	= 72, 	iconMenu	= 73, 	iconAccelOff	= 74, 	iconRestore	= 75, 
				iconFolder	= 76, 	iconLock	= 77, 	iconComp	= 78, 	iconCancel	= 79, 
				iconOk	= 80, 	iconPlay	= 81, 	iconMagic	= 82, 	iconCode	= 83, 
				iconFilter	= 84, 	iconPause	= 85, 	iconEject	= 86, 	iconTraceIn	= 87, 
				icon8	= 88, 	iconYes	= 89, 	iconSound	= 90, 	iconBps	= 91, 
				iconProps	= 92, 	iconGamepad	= 93, 	iconOpen	= 94, 	iconRom	= 95, 
				iconCasette	= 96, 	iconDisplay	= 97, 	iconNote	= 98, 	iconModel	= 99, 
				iconTurbo	= 100, 	iconCloud	= 101, 	iconWeb	= 102, 	iconLang	= 103, 
				iconPoke	= 104, 	iconTools	= 105, 	iconSettings	= 106, 	iconExit	= 107, 
				iconReset	= 108, 	iconDec	= 109, 	iconDelete	= 110, 	iconShiftFix	= 111, 
				iconShift	= 112, 	iconShiftPress	= 113, 			};
		}; 
		_integer integer;
		struct _string {
			enum { 
				app_name	= 0x00100006, 	acontrollerMap	= 0x00100007, 	ccontrollerMap	= 0x00100008, 
				themeDark	= 0x00100009, 	themeLight	= 0x0010000A, 	textSpan	= 0x0010000B, 
				first_form	= 0x0010000C, 	enter_family	= 0x0010000D, 	press_me	= 0x0010000E, 
				sergey	= 0x0010000F, 	progress	= 0x00100010, 	text_on_button	= 0x00100011, 
				mode_already	= 0x00100012, 	switcher	= 0x00100013, 	activate	= 0x00100014, 
				slider_text	= 0x00100015, 	prompt	= 0x00100016, 	radio_dark	= 0x00100017, 
				radio_light	= 0x00100018, 	checkbox_text	= 0x00100019, 	menuOpenSave	= 0x0010001A, 
				menuSettings	= 0x0010001B, 	menuProperties	= 0x0010001C, 
				menuSound	= 0x0010001D, 	menuPokes	= 0x0010001E, 	menuMru	= 0x0010001F, 
				menuOperations	= 0x00100020, 	menuReset	= 0x00100021, 	menuRestore	= 0x00100022, 
				menuExecute	= 0x00100023, 	menuExit	= 0x00100024, 	menuModel	= 0x00100025, 
				menuTurbo	= 0x00100026, 	menuFilter	= 0x00100027, 	menuTape	= 0x00100028, 
				menuDebugger	= 0x00100029, 	menuExeDebugger	= 0x0010002A, 
				menuMagic	= 0x0010002B, 	menuDisk1	= 0x0010002C, 	menuDisk2	= 0x0010002D, 
				menuDisk3	= 0x0010002E, 	menuDisk4	= 0x0010002F, 	menuSinclair48	= 0x00100030, 
				menuSinclair128	= 0x00100031, 	menuPentagon	= 0x00100032, 
				menuScorpion	= 0x00100033, 	menuMruEmpty	= 0x00100034, 	menuKeyJoy	= 0x00100035, 
				menuLabel	= 0x00100036, 	menuCode	= 0x00100037, 	menuValue	= 0x00100038, 
				menuQuickSave	= 0x00100039, 	menuAsm	= 0x0010003A, 	menuTzx	= 0x0010003B, 
				podskazka	= 0x0010003C, 	Perekljuchatelw	= 0x0010003D, 	slayder	= 0x0010003E, 
				Sergey	= 0x0010003F, 			};
		}; 
		_string string;
		struct _array {
			enum { 
				spinArray	= 0x00100040, 			};
		}; 
		_array array;
		struct _style {
			enum {
				keyboardBase	= 0x00100000, 	keyboardAlt	= 0x00100001, 	scrollbar	= 0x00100002, 
				glow	= 0x00100003, 	caret	= 0x00100004, 	editButClear	= 0x00100005, 
				tabs	= 0x00100006, 	tabContent	= 0x00100007, 	formFooterLyt	= 0x00100008, 
				formContentLyt	= 0x00100009, 	toast	= 0x0010000A, 	bar	= 0x0010000B, 
				barButton	= 0x0010000C, 	barOverflow	= 0x0010000D, 	menuImage	= 0x0010000E, 
				barPopup	= 0x0010000F, 	formCaption	= 0x00100010, 	formFooter	= 0x00100011, 
				spin_item	= 0x00100012, 	list_item	= 0x00100013, 	menu_item	= 0x00100014, 
				spin_capt	= 0x00100015, 	button	= 0x00100016, 	tools	= 0x00100017, 
				checkbox	= 0x00100018, 	radiobutton	= 0x00100019, 	edittext	= 0x0010001A, 
				ribbon	= 0x0010001B, 	grid	= 0x0010001C, 	select	= 0x0010001D, 
				msgForm	= 0x0010001E, 	slider	= 0x0010001F, 	linearProgress	= 0x00100020, 
				circularProgress	= 0x00100021, 	switchButton	= 0x00100022, 
				llinear	= 0x00100023, 	tabWidget	= 0x00100024, 	tabHost	= 0x00100025, 
				ccontroller	= 0x00100026, 	acontroller	= 0x00100027, 	form	= 0x00100028, 
				chart	= 0x00100029, 	chartDiagramm	= 0x0010002A, 	chartGraph	= 0x0010002B, 
				zcelllayout1	= 0x0010002C, 	list1	= 0x0010002D, 	edit1	= 0x0010002E, 
				button1	= 0x0010002F, 	switch1	= 0x00100030, 	seek	= 0x00100031, 
				progress1	= 0x00100032, 	zscrolllayout1	= 0x00100033, 	grid1	= 0x00100034, 
				zlinearlayout1	= 0x00100035, 	radiodark	= 0x00100036, 	chkbox	= 0x00100037, 
				radiolight	= 0x00100038, 	zviewedit1	= 0x00100039, 	zviewbutton1	= 0x0010003A, 
				zviewswitch1	= 0x0010003B, 	switch2	= 0x0010003C, 	switch3	= 0x0010003D, 
				zviewslider1	= 0x0010003E, 	seek1	= 0x0010003F, 	button11	= 0x00100040, 
				seek2	= 0x00100041, 	edit2	= 0x00100042, 	zlinearlayout2	= 0x00100043, 
				zlinearlayout3	= 0x00100044, 	zviewedit2	= 0x00100045, 	zviewbutton2	= 0x00100046, 
				zviewslider2	= 0x00100047, 	zviewslider3	= 0x00100048, 	zviewslider4	= 0x00100049, 
				zviewedit3	= 0x0010004A, 	zviewslider5	= 0x0010004B, 	zviewslider6	= 0x0010004C, 
	};
		};
		_style style;
	};
	_R R;
};

static _z z;

#include "zSystemStyles.h"

/* styles resources */
static zStyles z_styles[] = {
		{ _z::_R::_style::keyboardBase, styles_z_keyboardbase },
		{ _z::_R::_style::keyboardAlt, styles_z_keyboardalt },
		{ _z::_R::_style::scrollbar, styles_z_scrollbar },
		{ _z::_R::_style::glow, styles_z_glow },
		{ _z::_R::_style::caret, styles_z_caret },
		{ _z::_R::_style::editButClear, styles_z_editbutclear },
		{ _z::_R::_style::tabs, styles_z_tabs },
		{ _z::_R::_style::tabContent, styles_z_tabcontent },
		{ _z::_R::_style::formFooterLyt, styles_z_formfooterlyt },
		{ _z::_R::_style::formContentLyt, styles_z_formcontentlyt },
		{ _z::_R::_style::toast, styles_z_toast },
		{ _z::_R::_style::bar, styles_z_bar },
		{ _z::_R::_style::barButton, styles_z_barbutton },
		{ _z::_R::_style::barOverflow, styles_z_baroverflow },
		{ _z::_R::_style::menuImage, styles_z_menuimage },
		{ _z::_R::_style::barPopup, styles_z_barpopup },
		{ _z::_R::_style::formCaption, styles_z_formcaption },
		{ _z::_R::_style::formFooter, styles_z_formfooter },
		{ _z::_R::_style::spin_item, styles_z_spin_item },
		{ _z::_R::_style::list_item, styles_z_list_item },
		{ _z::_R::_style::menu_item, styles_z_menu_item },
		{ _z::_R::_style::spin_capt, styles_z_spin_capt },
		{ _z::_R::_style::button, styles_z_button },
		{ _z::_R::_style::tools, styles_z_tools },
		{ _z::_R::_style::checkbox, styles_z_checkbox },
		{ _z::_R::_style::radiobutton, styles_z_radiobutton },
		{ _z::_R::_style::edittext, styles_z_edittext },
		{ _z::_R::_style::ribbon, styles_z_ribbon },
		{ _z::_R::_style::grid, styles_z_grid },
		{ _z::_R::_style::select, styles_z_select },
		{ _z::_R::_style::msgForm, styles_z_msgform },
		{ _z::_R::_style::slider, styles_z_slider },
		{ _z::_R::_style::linearProgress, styles_z_linearprogress },
		{ _z::_R::_style::circularProgress, styles_z_circularprogress },
		{ _z::_R::_style::switchButton, styles_z_switchbutton },
		{ _z::_R::_style::llinear, styles_z_llinear },
		{ _z::_R::_style::tabWidget, styles_z_tabwidget },
		{ _z::_R::_style::tabHost, styles_z_tabhost },
		{ _z::_R::_style::ccontroller, styles_z_ccontroller },
		{ _z::_R::_style::acontroller, styles_z_acontroller },
		{ _z::_R::_style::form, styles_z_form },
		{ _z::_R::_style::chart, styles_z_chart },
		{ _z::_R::_style::chartDiagramm, styles_z_chartdiagramm },
		{ _z::_R::_style::chartGraph, styles_z_chartgraph },
		{ _z::_R::_style::zcelllayout1, styles_z_zcelllayout1 },
		{ _z::_R::_style::list1, styles_z_list1 },
		{ _z::_R::_style::edit1, styles_z_edit1 },
		{ _z::_R::_style::button1, styles_z_button1 },
		{ _z::_R::_style::switch1, styles_z_switch1 },
		{ _z::_R::_style::seek, styles_z_seek },
		{ _z::_R::_style::progress1, styles_z_progress1 },
		{ _z::_R::_style::zscrolllayout1, styles_z_zscrolllayout1 },
		{ _z::_R::_style::grid1, styles_z_grid1 },
		{ _z::_R::_style::zlinearlayout1, styles_z_zlinearlayout1 },
		{ _z::_R::_style::radiodark, styles_z_radiodark },
		{ _z::_R::_style::chkbox, styles_z_chkbox },
		{ _z::_R::_style::radiolight, styles_z_radiolight },
		{ _z::_R::_style::zviewedit1, styles_z_zviewedit1 },
		{ _z::_R::_style::zviewbutton1, styles_z_zviewbutton1 },
		{ _z::_R::_style::zviewswitch1, styles_z_zviewswitch1 },
		{ _z::_R::_style::switch2, styles_z_switch2 },
		{ _z::_R::_style::switch3, styles_z_switch3 },
		{ _z::_R::_style::zviewslider1, styles_z_zviewslider1 },
		{ _z::_R::_style::seek1, styles_z_seek1 },
		{ _z::_R::_style::button11, styles_z_button11 },
		{ _z::_R::_style::seek2, styles_z_seek2 },
		{ _z::_R::_style::edit2, styles_z_edit2 },
		{ _z::_R::_style::zlinearlayout2, styles_z_zlinearlayout2 },
		{ _z::_R::_style::zlinearlayout3, styles_z_zlinearlayout3 },
		{ _z::_R::_style::zviewedit2, styles_z_zviewedit2 },
		{ _z::_R::_style::zviewbutton2, styles_z_zviewbutton2 },
		{ _z::_R::_style::zviewslider2, styles_z_zviewslider2 },
		{ _z::_R::_style::zviewslider3, styles_z_zviewslider3 },
		{ _z::_R::_style::zviewslider4, styles_z_zviewslider4 },
		{ _z::_R::_style::zviewedit3, styles_z_zviewedit3 },
		{ _z::_R::_style::zviewslider5, styles_z_zviewslider5 },
		{ _z::_R::_style::zviewslider6, styles_z_zviewslider6 }
};

/* string resources [values] */
static zResource z_resources[] = {
		{ 0, "" },
		/* drawable */
		{ _z::_R::_drawable::font1, "font1" },
		{ _z::_R::_drawable::font2, "font2" },
		{ _z::_R::_drawable::font3, "font3" },
		{ _z::_R::_drawable::fontDefault, "fontDefault" },
		{ _z::_R::_drawable::znull, "znull" },
		{ _z::_R::_drawable::zssh, "zssh" },
		/* string */
		{ _z::_R::_string::app_name, "Programm" },
		{ _z::_R::_string::acontrollerMap, "acontrollerMap.xml" },
		{ _z::_R::_string::ccontrollerMap, "ccontrollerMap.xml" },
		{ _z::_R::_string::themeDark, "_dark" },
		{ _z::_R::_string::themeLight, "_light" },
		{ _z::_R::_string::textSpan, "Finish work background application after blocked screen helps saved battery." },
		{ _z::_R::_string::first_form, "First form!!!" },
		{ _z::_R::_string::enter_family, "Entering family" },
		{ _z::_R::_string::press_me, "Press me:)" },
		{ _z::_R::_string::sergey, "Sergey" },
		{ _z::_R::_string::progress, "Progress" },
		{ _z::_R::_string::text_on_button, "Text on the button" },
		{ _z::_R::_string::mode_already, "Mode of the already" },
		{ _z::_R::_string::switcher, "Switcher" },
		{ _z::_R::_string::activate, "Activate" },
		{ _z::_R::_string::slider_text, "Slider" },
		{ _z::_R::_string::prompt, "Prompt" },
		{ _z::_R::_string::radio_dark, "Dark theme" },
		{ _z::_R::_string::radio_light, "Light theme" },
		{ _z::_R::_string::checkbox_text, "Checkbox flags" },
		{ _z::_R::_string::menuOpenSave, "Browse..." },
		{ _z::_R::_string::menuSettings, "Settings..." },
		{ _z::_R::_string::menuProperties, "Properties..." },
		{ _z::_R::_string::menuSound, "Sound" },
		{ _z::_R::_string::menuPokes, "Pokes..." },
		{ _z::_R::_string::menuMru, "Last..." },
		{ _z::_R::_string::menuOperations, "Operations..." },
		{ _z::_R::_string::menuReset, "Reset" },
		{ _z::_R::_string::menuRestore, "Restore" },
		{ _z::_R::_string::menuExecute, "Executed" },
		{ _z::_R::_string::menuExit, "Exit" },
		{ _z::_R::_string::menuModel, "Model..." },
		{ _z::_R::_string::menuTurbo, "Turbo mode" },
		{ _z::_R::_string::menuFilter, "Filtered" },
		{ _z::_R::_string::menuTape, "Tape" },
		{ _z::_R::_string::menuDebugger, "Debugging" },
		{ _z::_R::_string::menuExeDebugger, "Debugger..." },
		{ _z::_R::_string::menuMagic, "MAGIC" },
		{ _z::_R::_string::menuDisk1, "A:" },
		{ _z::_R::_string::menuDisk2, "B:" },
		{ _z::_R::_string::menuDisk3, "C:" },
		{ _z::_R::_string::menuDisk4, "D:" },
		{ _z::_R::_string::menuSinclair48, "Sinclair 48K" },
		{ _z::_R::_string::menuSinclair128, "Sinclair 128K" },
		{ _z::_R::_string::menuPentagon, "Pentagon 512K" },
		{ _z::_R::_string::menuScorpion, "Scorpion 256K" },
		{ _z::_R::_string::menuMruEmpty, "Empty" },
		{ _z::_R::_string::menuKeyJoy, "Keyboard/Joystick" },
		{ _z::_R::_string::menuLabel, "Label" },
		{ _z::_R::_string::menuCode, "Code" },
		{ _z::_R::_string::menuValue, "Content" },
		{ _z::_R::_string::menuQuickSave, "QuickSave" },
		{ _z::_R::_string::menuAsm, "Assembler" },
		{ _z::_R::_string::menuTzx, "Editor TZX" },
		{ _z::_R::_string::podskazka, "подсказка" },
		{ _z::_R::_string::Perekljuchatelw, "Переключатель" },
		{ _z::_R::_string::slayder, "слайдер" },
		{ _z::_R::_string::Sergey, "Sergey" },
		/* array */
		{ _z::_R::_array::spinArray | ZT_END, "Ivan|Irina|Sergey Shatalov|Maxim|Vladislav|06.06.1979|Shatalov Sergey|Olga|Viktor Alexeevich|Cat|Maria|Nina Shatalova|Alex|Alexandr" }
};

/* string resources [values_ru] */
static zResource z_resources_ru[] = {
		{ 0, "ru" },
		/* string */
		{ _z::_R::_string::app_name, "Программа" },
		{ _z::_R::_string::textSpan, "Завершение работы фоновых приложений после блокировки экрана помогает экономить заряд. С другой стороны, в этом случае вы не будете получать новые сообщения (электронные, текстовые, из соцсетей и т.д.)." },
		{ _z::_R::_string::first_form, "Первая форма!!!" },
		{ _z::_R::_string::enter_family, "Введите фамилию и отчество" },
		{ _z::_R::_string::press_me, "Нажми на меня:)" },
		{ _z::_R::_string::sergey, "Сергей" },
		{ _z::_R::_string::progress, "Прогресс" },
		{ _z::_R::_string::text_on_button, "Текст на кнопке" },
		{ _z::_R::_string::mode_already, "Режим готовности" },
		{ _z::_R::_string::switcher, "Переключатель" },
		{ _z::_R::_string::activate, "Активация" },
		{ _z::_R::_string::slider_text, "слайдер" },
		{ _z::_R::_string::prompt, "Подсказка" },
		{ _z::_R::_string::radio_dark, "Темная" },
		{ _z::_R::_string::radio_light, "Светлая" },
		{ _z::_R::_string::checkbox_text, "Флажок" },
		{ _z::_R::_string::menuOpenSave, "Менеджер..." },
		{ _z::_R::_string::menuSettings, "Установки..." },
		{ _z::_R::_string::menuProperties, "Свойства..." },
		{ _z::_R::_string::menuSound, "Звук" },
		{ _z::_R::_string::menuMru, "Последние..." },
		{ _z::_R::_string::menuReset, "Сброс" },
		{ _z::_R::_string::menuRestore, "Восстановить" },
		{ _z::_R::_string::menuOperations, "Операции..." },
		{ _z::_R::_string::menuExecute, "Выполнение" },
		{ _z::_R::_string::menuExit, "Выход" },
		{ _z::_R::_string::menuModel, "Модель..." },
		{ _z::_R::_string::menuTurbo, "Турбо режим" },
		{ _z::_R::_string::menuFilter, "Фильтрация" },
		{ _z::_R::_string::menuTape, "Магнитофон" },
		{ _z::_R::_string::menuDebugger, "Отладка" },
		{ _z::_R::_string::menuExeDebugger, "Отладчик..." },
		{ _z::_R::_string::menuSinclair48, "Синклер 48K" },
		{ _z::_R::_string::menuSinclair128, "Синклер 128K" },
		{ _z::_R::_string::menuPentagon, "Пентагон 512K" },
		{ _z::_R::_string::menuScorpion, "Скорпион 256K" },
		{ _z::_R::_string::menuMruEmpty, "Пусто" },
		{ _z::_R::_string::menuKeyJoy, "Клавиатура/Джойстик" },
		{ _z::_R::_string::menuLabel, "Метки" },
		{ _z::_R::_string::menuCode, "Код" },
		{ _z::_R::_string::menuValue, "Содержимое" },
		{ _z::_R::_string::menuQuickSave, "QuickSave" },
		{ _z::_R::_string::menuAsm, "Ассемблер" },
		{ _z::_R::_string::menuTzx, "Редактор TZX" },
		/* array */
		{ _z::_R::_array::spinArray | ZT_END, "Иван|Ирина|Сергей Викторович|Максим|Владислав|06.06.1979|Шаталов Сергей|Ольга|Виктор Алексеевич|Катя|Маша|Нина Шаталова|Алекс|Саша" }
};


static zResource* z_resources_ptr_arrays[] = { z_resources, z_resources_ru, nullptr };

// menu
static MENUITEM main_menu[] = {
	{ menuItem, z.R.integer.MENU_KEYBOARD, z.R.string.menuKeyJoy, z.R.integer.iconKeyb, menuItemText | actAlways },
	{ menuGroupBegin, z.R.integer.MENU_DEBUGGER1, z.R.string.menuDebugger, z.R.integer.iconDebug, menuItemText | actAlways },
		{ menuItem, z.R.integer.MENU_DEBUGGER_LABEL, z.R.string.menuLabel, z.R.integer.iconDebug, menuItemCheck },
		{ menuItem, z.R.integer.MENU_DEBUGGER_CODE, z.R.string.menuCode, z.R.integer.iconCode, menuItemCheck },
		{ menuItem, z.R.integer.MENU_DEBUGGER_VALUE, z.R.string.menuValue, z.R.integer.iconContent, menuItemCheck },
	{ menuGroupEnd },
	{ menuItem, z.R.integer.MENU_BROWSER, z.R.string.menuOpenSave, z.R.integer.iconOpen, menuItemText | actAlways },
	{ menuItem, z.R.integer.MENU_SETTINGS, z.R.string.menuSettings, z.R.integer.iconSettings, menuItemText | actAlways },
	{ menuGroupBegin, z.R.integer.MENU_PROPS, z.R.string.menuProperties, z.R.integer.iconProps, menuItemText | actAlways },
		{ menuItem, z.R.integer.MENU_PROPS_SOUND, z.R.string.menuSound, z.R.integer.iconSound, menuItemCheck },
		{ menuItem, z.R.integer.MENU_PROPS_MAGNITOPHON, z.R.string.menuTape, z.R.integer.iconCasette, menuItemCheck },
		{ menuItem, z.R.integer.MENU_PROPS_FILTER, z.R.string.menuFilter, z.R.integer.iconFilter, menuItemCheck },
		{ menuItem, z.R.integer.MENU_PROPS_TURBO, z.R.string.menuTurbo, z.R.integer.iconTurbo, menuItemCheck },
		{ menuItem, z.R.integer.MENU_PROPS_EXECUTE, z.R.string.menuExecute, z.R.integer.iconLock, menuItemCheck },
		{ menuItem, z.R.integer.MENU_PROPS_DEBUGGER, z.R.string.menuDebugger, z.R.integer.iconDebug, menuItemCheck },
	{ menuGroupEnd },
	{ menuGroupBegin, z.R.integer.MENU_MODEL, z.R.string.menuModel, z.R.integer.iconModel, menuItemText | actIfRoom },
		{ menuItem, z.R.integer.MENU_MODEL_48KS, z.R.string.menuSinclair48, z.R.integer.iconComp, menuItemRadio },
		{ menuItem, z.R.integer.MENU_MODEL_128K, z.R.string.menuSinclair128, z.R.integer.iconComp, menuItemRadio },
		{ menuItem, z.R.integer.MENU_MODEL_PENTAGON, z.R.string.menuPentagon, z.R.integer.iconComp, menuItemRadio },
		{ menuItem, z.R.integer.MENU_MODEL_SCORPION, z.R.string.menuScorpion, z.R.integer.iconComp, menuItemRadio },
	{ menuGroupEnd },
	{ menuGroupBegin, z.R.integer.MENU_OPERATIONS, z.R.string.menuOperations, z.R.integer.iconNote, menuItemText | actIfRoom },
		{ menuItem, z.R.integer.MENU_POKES, z.R.string.menuPokes, z.R.integer.iconPoke, menuItemText },
		{ menuItem, z.R.integer.MENU_RESET, z.R.string.menuReset, z.R.integer.iconReset, menuItemText },
		{ menuItem, z.R.integer.MENU_RESTORE, z.R.string.menuRestore, z.R.integer.iconRestore, menuItemText },
		{ menuItem, z.R.integer.MENU_ASSEMBLER, z.R.string.menuAsm, z.R.integer.iconRom, menuItemText },
		{ menuItem, z.R.integer.MENU_EDITOR_TZX, z.R.string.menuTzx, z.R.integer.iconTzx, menuItemText },
		{ menuItem, z.R.integer.MENU_MAGIC, z.R.string.menuMagic, z.R.integer.iconMagic, menuItemText },
	{ menuGroupEnd },
	{ menuGroupBegin, z.R.integer.MENU_MRU, z.R.string.menuMru, z.R.integer.iconMru, menuItemText | actIfRoom },
		{ menuItem, z.R.integer.MENU_MRU_1, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_2, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_3, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_4, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_5, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_6, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_7, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_8, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_9, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
		{ menuItem, z.R.integer.MENU_MRU_10, z.R.string.menuMruEmpty, z.R.integer.iconMru, menuItemText },
	{ menuGroupEnd },
	{ menuItem, z.R.integer.MENU_SHOW_DEBUGGER, z.R.string.menuExeDebugger, z.R.integer.iconDebug, menuItemText | actNever },
	{ menuItem, z.R.integer.MENU_EXIT, z.R.string.menuExit, z.R.integer.iconExit, menuItemText | actNever },
	{ menuEnd }
};

